### ISSUE TITLE
Add tests and README for `mergedHtmlPrefix` and `defaultHtml`

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#10]
To meet fully featured and flexible behavior for https://github.com/Starcounter/Starcounter/issues/3539 (and https://github.com/Starcounter/starcounter-include/issues/9) I have implemented features
1. to change merged HTML prefix from `/sc/htmlmerger?` to something else - this could be done by `mergedHtmlPrefix` property,
2. to provide default URL if there is no `Html` property on namespace level (for example to stamp JSON as text or `<juicy-jsoneditor>`) - this could be done by `defaultHtml` property

We need 
- [ ] test suite and 
- [ ] nice README for that,

We can also consider
- [ ] handle it via attribute (not only via Polymers property binding)

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
