### ISSUE TITLE
Clearer warning messages

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#107]
@mmnosek would like me to propose clearer warning messages instead of:

```
starcounter-include.html:16 `partial` attribute and property are deprecatrd from `starcounter-include` in fovour of (viewModel property or view-model attribute), they will soon be no longer be supported
```

and 

```
starcounter-include.html:451 Your view-model is probably not namespaced!
Proxy
We no longer support those.
Please make sure it's a result of `Self.GET` on serverside. If it's not a result of blending, then replace `<starcounter-include view-model="{{viewModel}}">` with  `<div><imported-template model="{{viewModel}}" href="{{viewModel.Html}}"></imported-template></div>`.
```

**Comment by mmnosek** [comment]
Personally, I would prefer to have a solution first. Then more detailed explanation can be included later.

**Comment by tomalec** [comment]
Here is more elaborate explanation what was changed, and how to deal with it https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/

**Comment by warpech** [comment]
> Personally, I would prefer to have a solution first. Then more detailed explanation can be included later.

I thought we agreed that the solution is actually included in the warning message, the only problem is that it is unclear? Or am I missing something?

**Comment by mmnosek** [comment]
You are not missing anything. What I meant here is that Solution should be provided immediately. So for instance:

```
starcounter-include.html:451 <starcounter-include...> is meant to be used only with blending (self-get). If it's not a result of blending, please replace it to <imported-template>. 
```

And maybe link to the explenation provided by @tomalec ?

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
