### ISSUE TITLE
starcounter-include should ignore responses without HTML

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-include#11]
Right now it sends a request with empty value:

```
http://localhost:8080/sc/htmlmerger?Launcher=&SignIn=%2FSignIn%2Fviewmodels%2FSignInPage.html
```

cc @tomalec, @warpech

**Comment by tomalec** [comment]
AFAIR this is desired feature.
You can specify [`defaultHTML` (#10)](https://github.com/Starcounter/starcounter-include/issues/10) property to give a default renderer if not given.

If there is no partial for given JSON, a launcher could provide for example `<juicy-jsoneditor>` for faster development/debugging.

**Comment by miyconst** [comment]
Yes, but if there is no `Html` and no `defaultHTML` what for to add an empty parameter to the url?

**Comment by tomalec** [comment]
> what for to add an empty parameter to the url?

So server-side HTML merger could decide what to do, and add something if needed. For example, we may decide that server-side should decide what "default renderer" should be used.

Is there any harm/problem done because of such empty Html?  

I believe such design is simpler. `sc-include` forward all information that it have to `htmlmerger` without "filtering empty namespaces".

As later on somebody could say: "starcounter-include hides my namespace from htmlmerger"

**Comment by miyconst** [comment]
In spite of I don't see how we can effectively use it to display a default view, as on server side we have nothing except the app name which is missing an html template, but the arguments make sense.

I close the issue.

**Comment by tomalec** [comment]
> In spite of I don't see how we can effectively use it to display a default view, as on server side we have nothing except the app name which is missing an html template, but the arguments make sense.

Our Launcher could provide `<template><juicy-jsoneditor json="{{model}}"></juicy-json-editor></template>` as a default view (either via replacing `<starcounter-include>` or via `htmlmerger`).

Tunity's Launcher on the other case could serve `<template><tunity-mock-view json="{{model}}"></tunity-mock-view><tunity-statistics-tool></tunity-statistics-tool></template>`

**Comment by miyconst** [comment]
Yes, but the "default" view will always be there for partials without HTML, which is not always desired.

**Comment by tomalec** [comment]
But sometimes it is desired, so it will be always available. 

We are not forcing anybody to use it, to use particular Launcher, or particular feature. It's better to expose more flexibility and not use it, rather than block ourselves.
