### ISSUE TITLE
Events names are confusing and messy

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#110]
Related to https://github.com/Juicy/imported-template/issues/54, but we have some mess here as well.

To summarize:

- `imported-template` dispatches:
  - `stamped` when HTML Import with partial view is added, before anything is loaded - Should be called somewhat like `importing`
  - `stamping` when HTML Import with partial view is being processed

- `starcounter-include` dispatches
   - `partial-changed`, `view-model-changed`, `starcounter-include-composition-saved` when composition is saved - those events and functionality should be moved outside of `starcounter-include`
   - `stamped` when composition is stamped - should be called, like `presentation-stamped`

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
