### ISSUE TITLE
`imported-template` may receive new model for old view

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#112]
### Steps to reproduce
1. Stamp `starcounter-include` from `dom-bind`,
2. Change entire `view-model` to one that changes href of a view,
3. Change entire `view-model` to one that has the same view, but do it before the view from 2. is loaded.
4. Check the model of old view elements before new view is loaded

### Expected result
There should be old model (from step 1) attached

### Actual result
The new model (from step 3) is attached

### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8
- [?] IE 11

**Comment by tomalec** [comment]
It seems we had an incorrectly implemented test that should fail https://github.com/Starcounter/starcounter-include/commit/dbc5e50f265bb8fcd2c790b6ce26e0abbbbc5901#diff-d2023b39f944df7b221779867b7533f6R209

**Comment by warpech** [comment]
We discussed today with @tomalec that he will first attempt fixing that by changing Polymer binding code in `palindrom-client`. If that fails, he will consider removing single `imported-template` with multiple scopes with multiple `imported-template`s.

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
