### ISSUE TITLE
Undesired/unspecified behavior when entire scope is changed and that changes URL

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#113]
Currently when one scope is changed in a model, we start fetching new content, and keep the old view with the old **root** model still attached, that means the old view has the new data. We will defer propagation of Polymer bindings until the content is loaded, but the model is already changed, and some separate actions may consume it.
(what is one of many reasons of https://github.com/Starcounter/HeadsOmni/issues/223)

The current architecture does not allow much move here, as view and model are glued together in JSON, plus `i-t` process the entire model at once.

That is another problem to consider in https://github.com/Starcounter/RebelsLounge/issues/97

I have an idea to change the way `imported-template`/`starcounter-include` processes scopes and nested view models. We could make it more explicit and verbose. 

So we will have a real custom element (`imported-template`) per each scope individually, not just a mock marker - `imported-template-scope`. Then every element could control model and view changes separately from the entire merged view-model. `starcounter-include` will still attach shadow DOM compositions to their, shared container. To stamp those per-scope `imported-tempalte`s we could use parent `imported-tempalte` or implement that in `starcounter-include`.

Hopefully the maintainability, and isolated data flow would pay off the const of `n` more nodes per `imported-template`, where `n` is number of scopes.

//cc @warpech @alshakero

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
