### ISSUE TITLE
Research binding to the data within compositions

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#117]
Consider binding to the data within compositions. This will be useful to create conditional compositions, etc.

**Comment by warpech** [comment]
@alshakero can you think of what would be the consequences of this? I can think of at least now:

In the source code of HTML compositions that is allowed to use data binding, you will obviously want to use things like `dom-if`. The popup composition editor will mess things up, because it considers `innerHTML` to be equivalent of the source code, while it is not. For example, you want `<template is="dom-if">` in the source code, but not the stamped result of it.

Can you work on initial implementation:

- starcounter-layout-html-editor that works on the source code instead of `innerHTML` of shadow root (this also solves problem https://github.com/Starcounter/RebelsLounge/issues/388)
- starcounter-include that allows data binding in shadow root

Preferably in two separate PRs.

**Comment by warpech** [comment]
On the Group One meeting 2018-12-19 it was decided that we will not implement this, for the following reasons: 

- the path to data would need to include the application namespace, which is an implementation detail
- data binding code in the composition part would fail to compile if the app is stopped and the view-model is missing

The implementation of the atoms (https://github.com/Starcounter/RebelsLounge/issues/395) should reduce the need for data binding in the custom compositions.

**Comment by tomalec** [comment]
However, the view of individual atom, could be changed with pro-blending-editor. There solution owner/designer could use data binding with model and semantics data, as well as, light and shadow DOM.

**Comment by warpech** [comment]
Follow up: https://github.com/Starcounter/Blending/issues/408
