### ISSUE TITLE
Add a test for rendering default views for the missing views in a subset custom composition

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#125]
As explained in https://github.com/Starcounter/starcounter-include/pull/123#discussion_r278310702, the starcounter-include tests do not catch if this works correctly.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Blending/issues/571

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
