### ISSUE TITLE
starcounter-include ignore changes on Html properties of partials

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-include#13]
Changing an `Html` property of a partial after it's loaded does not updated `<imported-template>` inside `<starcounter-include>`.

cc @tomalec, @warpech

**Comment by tomalec** [comment]
Could you prepare something to reproduce it?

We have a test for it, that passes
https://github.com/Starcounter/starcounter-include/blob/gh-pages/test/partialAttribute/nested-html/stamped_from_polymer_template.html#L100

**Comment by miyconst** [comment]
I can't reproduce it locally. Will open the bug again once find a way to reproduce it.
