### ISSUE TITLE
Performance improvement idea for merged default compositions

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#15]
> _moved from https://github.com/StarcounterPrefabs/launcher-include/issues/19_

If it will occur that keeping a clone of merged default composition on `<starcounter-include>.defaultComposition` is a performance hit, we could:
1. Keep merged default layouts on HTML Imported document level, se each instance of `<starcounter-include>` referring same document/partial could clone it from there without a need to merge it and store it by itself,
2. Merge once needed:
   Pros: 
   - we will not have to lock the memory for storing the clones,
     Cons:
   - each (re-)stamp of the same partial will require building/merging the Document Fragment

See https://github.com/StarcounterPrefabs/launcher-include/issues/18 - cloning implemented there was an inspiration for this idea.

**Comment by miyconst** [comment]
Not relevant for Starcounter 3.
