### ISSUE TITLE
Support slot tag (future compatibility)

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#19]
> Part of umbrella: https://github.com/Starcounter/RebelsLounge/issues/81

As we are heading towards webcomponents v1, and we would like to migrate gently, we should already start to support `<slot>` tags in our partials' (views') Shadow DOM Compositions.. The idea is that, we will allow app developers to prepare those compositions using basic v1 syntax, even though we will still use v0 underneath, so we would replace `<slot name="smth">` with `<content select='[slot="my-slot"]'>` in `stracounter-include`.

My only doubt is about CSS selectors, as I would prefer not to change it automatically, but rather assume it was already written to us both selectors.
https://github.com/Starcounter/RebelsLounge/issues/72.

Once implemented, we would need to announce it properly.

**Comment by warpech** [comment]
We had a Hangouts discussion if this change is needed right now or now. I believe that the conclusion was that it is better to write `::content`, `::slotted`, `<content>`, `<slot>` explicitly, or was it other?

For the actual JS code, I believe that @alshakero is a better reviewer than me.

**Comment by tomalec** [comment]
Right, let's put it on hold for a moment

**Comment by tomalec** [comment]
Done, via https://github.com/Juicy/juicy-composition/pull/5
