### ISSUE TITLE
Alias `partial` with `view-model`

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#21]
To meet our renaming ideas https://github.com/Starcounter/TechComm/issues/286
and be closer to MVVM terminology, as an alternative to 
```html
<starcounter-include partial="{{JSONwithData}}"></starcounter-include>
```
we could write
```html
<starcounter-include view-model="{{JSONwithData}}"></starcounter-include>
```

**Comment by tomalec** [comment]
@warpech WDYT about pushing it to 2.3?

**Comment by warpech** [comment]
Please try to make a PR and we will see.
