### ISSUE TITLE
Race condition between view HTML importing and view-model attaching

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#25]
### Steps to reproduce
1. Use `<starcounter-include view-model="{{something}}">`.
2. Change `something` to a new partial view model with new HTML and new data.

#### Live Demo

https://jsbin.com/ligimo/3/edit?html,output

### Expected result
1. Markup should be loaded, **then**
2. New model should be attached to it.
### Actual result
1. Markup is requested
2. New model is attached to the **old** markup
3. Error is throws:
   ```log
   Invalid value used as weak map key
   ```
4. New markup is loaded
5. New model is attached to new markup

### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Screenshot
![2017-03-07 01_10_15-polymer-mini html c__program files_starcounter_clientfiles atom](https://cloud.githubusercontent.com/assets/566463/23636013/67ce1906-02d3-11e7-83c0-0016cb0b516c.png)

![2017-03-07 01_10_44-locationapp](https://cloud.githubusercontent.com/assets/566463/23635979/274524c4-02d3-11e7-82c2-0b48912765a8.png)

### Related

https://github.com/RemoteCloud/SystemLocationApp/issues/8
https://github.com/Juicy/imported-template/issues/24
https://github.com/Juicy/juicy-html/issues/10
possibly https://github.com/Juicy/imported-template/issues/26#issuecomment-279549037

**Comment by tomalec** [comment]
_Comment by @tomalec moved from https://github.com/RemoteCloud/SystemLocationApp/issues/8#issuecomment-285033549_

@warpech This is something with `imported-template`  (and `juicy-html`) we need to discuss, as the flow looks as follows

1. Server responds with `{op: 'replace', path: '/path/CurrentPage', value: {Html: 'new/url.html', data: {newdata:"smth"}`.
2. Entire binding chain, **synchronously** sets both attributes, on `imported-template`: `content` and `model`.
3. `imported-template` synchronously, sends **asynchronous** request for new markup, and 
4. **synchronously** sets new model to (old) markup.

I see few solutions:
1. `starcounter-include` should wait with attaching `model` until, new content is effectively loaded.
2. `imported-template` should detach markup when new markup is requested.
3. `imported-template` should block attaching new model when request is pending.

Related issues:
https://github.com/Juicy/imported-template/issues/24
https://github.com/Juicy/juicy-html/issues/10

**Comment by tomalec** [comment]
_Comment by @warpech moved from https://github.com/RemoteCloud/SystemLocationApp/issues/8#issuecomment-285341750_

We discussed with @tomalec that solution 1. is the most elegant one.

**Comment by jwillmer** [comment]
Any progress?

**Comment by tomalec** [comment]
Should be done today EOD

**Comment by tomalec** [comment]
Sorry for the delay, I have to redesign and rewrite all the tests. Hopefully, one day more would be enough.

**Comment by jwillmer** [comment]
> Sorry for the delay, I have to redesign and rewrite all the tests. Hopefully, one day more would be enough.

Is it?

**Comment by tomalec** [comment]
Sorry I was delayed by some other issues. PR with the fix is already waiting for the review.

**Comment by tomalec** [comment]
New build available at http://downloads.starcounter.com/download/Starcounter/RC/2.3.0.6170
