### ISSUE TITLE
Use `declarative-shadow-dom` custom element once ready

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#26]
> Part of umbrella: https://github.com/Starcounter/RebelsLounge/issues/81

Once it will be ready we should switch from `<juicy-composition><template is="declarative-shadow-dom">` (Juicy/juicy-composition) and the magic done by `juicy-composition` to just `<template is="declarative-shadow-dom">` <https://github.com/Starcounter/RebelsLounge/issues/78

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
