### ISSUE TITLE
Rename to starcounter-include

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#3]
As discussed in today meeting, the technology is named "Starcounter" and so should be all the APIs.

This also involves renaming the related docs and Launcher's polyjuice-include

**Comment by miyconst** [comment]
Should the main `Polyjuice` GitHub repository be also removed/renamed?

**Comment by warpech** [comment]
Yes

**Comment by miyconst** [comment]
- [x] `polyjuice-include` updated.
- [x] `launcher-include` updated.
- [x] `Polyjuice\StaticFiles\sys` updated.
- [x] Polyjuice applications updated.

Looks like nothing more left. Keeping the issue opened till next nighty build to test.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/starcounter.io/issues/27

**Comment by miyconst** [comment]
Tested with `2.0.3290.3` nighty build. Works good.

**Comment by warpech** [comment]
Good job! :+1:
