### ISSUE TITLE
JSON response is not presented if it does not have a `Html` property

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#33]
Follow up to: https://github.com/Starcounter/level1/issues/4145 and https://github.com/StarcounterApps/Launcher/issues/176.

The problem is that when a nested JSON does not have `Html` property, it is not rendered at all. The developer experience is really bad, causing a lot of time wasted on debugging.

## Current status (nested Json)

1. Edit the file `ExpenseJson.json` in HelloWorld@1fc5be8f43c793fa5649366333be735dad6457ac to contain `html` instead of `Html`.
2. Build and run Hello World
4. Go to `localhost:8080/helloworld`
5. Press the "Add expense" button

This is where the problem appears. You get the nested response when clicking on the "Add expense" button, but it is not rendered!

![2017-06-01 12_20_19-helloworld](https://cloud.githubusercontent.com/assets/566463/26675644/08a3489e-46c5-11e7-9f11-ef29521358b6.png)

---

## Proposed solution

When a JSON namespace does not have a `Html` property, `starcounter-include` should render the JSON in a JSON tree view, with the information that this is a fallback view presented because `Html` property was not found.

@tomalec WDYT?

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/starcounter-include/issues/12

**Comment by tomalec** [comment]
In general, without deep investigation, I think it's yet another bug in Website app.
I don't like the idea of pushing too many workarounds and hacks into sc-include, as it breaks unix principle.

I would imagine the Fallback JSON View to be just an app/system app, that may be disabled on production. Sometimes you may imagine use cases when you would like to return just a JSON as a source of data, without any visual representation.

I would really appreciate HO call with someone how could guide me through website app magic.

**Comment by tomalec** [comment]
Imagine the case:

```html
<my-fancy-VR-game>
  <player-details="{{model.Person}}"></player-details>
</my-fancy-VR-game>
```
So the app dev is using his/her own custom element to handle partial.

Then Images App could deliver HTML `<img>` with player's avatar, but
VR Game app would deliver just JSON with numeric HP and XP, that will be rendered somewhat different.

I don't think we should limit app devs, just to remind developer that he/she forgot to attach the view he/she wants to display.

**Comment by warpech** [comment]
> I would really appreciate HO call with someone how could guide me through website app magic.

It is not a website app magic. Quote: "Build and run WebsiteProvider or not. Doesn't matter here"

It is a problem with any nested JSON that does not have a **Html** property, reproducible even with a single app (see the instruction at **Current status (nested Json)**)

My mistake to even include Website in the description, I will shorten it.

**Comment by warpech** [comment]
> Fallback JSON View to be just an app/system app

This violates the principle of view-model isolation, because an app does not have access to JSON coming from another app. Of course we can write an app that violates that principle. But this does not solve the problem that it is difficult to recover from a typo (like `Htlm`) if you are developing an app and not running any other apps.

**Comment by warpech** [comment]
I have shortened the reproduction instructions to exclude Website.

**Comment by tomalec** [comment]
> This violates the principle of view-model isolation, because an app does not have access to JSON coming from another app.

Fair point, but with your proposition `sc-include` => host app that uses `sc-include` violates it anyways.

> But this does not solve the problem that it is difficult to recover from a typo (like `Htlm`) if you are developing an app and not running any other apps.

I appreciate the case to recover from typos, as I made hundreds of them by myself ;)
But does you mean we should **require** an app to have **HTML** view?

I see current recovery path as:
 0. I see no rendered result,
 1. I check the HTML source, there is none,
 2. I check the requested file, there is none,
 3. Oh! I didn't gave it.

Do you really think it's complicated an un-intuitive, I would compare it to the scenario, when you forgot to add `<script>` tag or misspelled it `<script scr="">` and you don't see the executed code results.

-----

If the case is "Give me the tool to write HTML-less, but functional prototype of my app" then I believe it's a separate discussion and I would design it as configurable (develop environment config) feature of Starcounter

**Comment by warpech** [comment]
Looking at the issue https://github.com/Starcounter/level1/issues/4145 I think that cumulatively more than a week of developer's time was wasted on investigating problems due to a typo or accidental omission of `Html` property. Including both the customers and our support devs.

Also, having a (interactive?) JSON preview by default would be a nice developer experience, leading to clear progression path: functioning server side code -> functioning client side code.

> But does you mean we should require an app to have HTML view?

Yes, my opinion is that in 99% cases (or maybe all cases that I've seen so far) it makes no sense to attach a response to `Blender.MapUri` that does not include a renderable `Html` property. The reason is that you are *indirectly* responding to a `text/html` request, so why would you not give a HTML response?

An exception might be that:

1. you are building a canvas-based video game that is rendered using several apps (where one of the apps acts like the renderer, others provide the data)
2. you are building a React Native app that somehow uses attached data from other apps, but it is rendered by the root app
3. you have another reason that I cannot foresee right now

In cases 1 and 2 the view is rendered by canvas or React Native, so `starcounter-include` does not even play a role.

In case 3, you can provide an empty value () `"Html": ""` to not trigger the JSON preview. Or you can hide the JSON preview using Declarative Shadow DOM.

----

Perhaps let's discuss that with @miyconst (author of #12) on the next Blending TF meeting?

**Comment by warpech** [comment]
> Yes, my opinion is that in 99% cases

OK. CompositionProvider actually falls within the other 1% :hushed: It is because it provides the metadata to `starcounter-include`.

It could be solved by providing `"Html": ""`

**Comment by warpech** [comment]
I just learned that there is a property `defaultURL` (docs here: https://github.com/Starcounter/starcounter-include/issues/10), which is used to provide a default view for namespaces without a view. Should this be used in case proposed above?

**Comment by warpech** [comment]
Closing. This should be solved on server-side. See: https://github.com/Starcounter/RebelsLounge/issues/97#issuecomment-319623042

**Comment by tomalec** [comment]
At blending TF meeting we agreed to support non-HTML views, where lack of `.Html` property is desired. That's why we should not force rendering them. Unless specified to be for example `HtmlViewModel,` instead of just `TypedJSON` (see https://github.com/Starcounter/RebelsLounge/issues/97)
