### ISSUE TITLE
Generic name of this repo

### ISSUE THREAD

**Issue by k-rus** [Starcounter/starcounter-include#35]
The name  of this repo is general for Starcounter, which means that the name cannot be used for any other includes than the purpose of this repo. This might result in confusion in future. May be the repo can be renamed in something, which is more connected to its purpose, while keeping this name for actual artifact?

**Comment by warpech** [comment]
What do you mean as "actual artifact"?

**Comment by tomalec** [comment]
Just to give short rationale of the current name:
It's the custom element name and that is common practice to name the repo as the element. Few years ago we had long discussion of the element name, and we didn't came up with better name. The key is that it has to be short.

**Comment by warpech** [comment]
Archiving
