### ISSUE TITLE
Migrate to CE v1

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#39]
> Part of umbrella: https://github.com/Starcounter/RebelsLounge/issues/81

As we now are capable to run CEv1 element in our v0 environment, I would start with migrating this one.

Given that we are planing to do vast amount of changes, which will more or less totally refactor existing element, I'd like to migrate it now, so we will not have to do same job twice and I will have to bother about life-cycle problems in up to date spec.

Related issues: 
 - https://github.com/Starcounter/RebelsLounge/issues/78
 - https://github.com/Starcounter/starcounter-include/issues/26
 - https://github.com/Starcounter/starcounter-include/issues/38
 - https://github.com/Starcounter/starcounter-include/issues/37
 - https://github.com/Starcounter/starcounter-include/issues/32
 - https://github.com/Starcounter/starcounter-include/issues/29
 - https://github.com/Starcounter/starcounter-include/issues/34

It may slightly affect polyfilled browsers performance, as we will have to apply two polyfills for this element.
But it won't be an issue, once we will move to full v1 polyfill, or browsers will support CE v1

//cc @Starcounter/sc-blendingtf  @warpech

**Comment by warpech** [comment]
@tomalec will make this an autonomous CEv1. The work is already started in https://github.com/Starcounter/starcounter-include/tree/CEv1.

We need a release candidate (can be without tests) ASAP.

Warning: shadow DOM should be tested in Safari and Chrome on iOS.

**Comment by warpech** [comment]
Closing as released in 4.0.0: https://github.com/Starcounter/starcounter-include/releases/tag/4.0.0

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/starcounter-include/releases/tag/4.0.0
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.0.0
