### ISSUE TITLE
Update wiki and readme pages

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-include#4]
Started issue: https://github.com/Polyjuice/starcounter-include/issues/3

There are a few wiki pages which should be updated, as we no longer have `polyjuice-include`.
- [x] https://github.com/Polyjuice/Launcher/wiki/include-template-in-Polyjuice
- [x] https://github.com/Polyjuice/Launcher/wiki/Partials
- [x] https://github.com/Polyjuice/Launcher/wiki/Polyjuice-knowledge
- [x] https://github.com/Polyjuice/launcher-include/blob/gh-pages/README.md

Maybe some more.

cc @warpech, @tomalec

**Comment by warpech** [comment]
Thanks for finding this. Can you update them?

**Comment by miyconst** [comment]
Yes.

Similar issue: https://github.com/Starcounter/starcounter.io/issues/25

**Comment by miyconst** [comment]
What to do with the page URLs? If I rename url, then the previous one won't be accessible.

Maybe move content to starcounter.io instead of editing on GitHub WiKi?

**Comment by miyconst** [comment]
`polyjuice-include` replaced with `starcounter-include`, `Polyjuice app` is replaced with `Starcounter app` on this page: https://github.com/Polyjuice/Launcher/wiki/Polyjuice-knowledge.

Others left as is. The content should be reworked and moved to starcounter.io, which is not part of this issue. Closing this issue.
