### ISSUE TITLE
Out dated links in README.md

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#40]
It seems we have quite outdated links in this README.md https://github.com/Starcounter/starcounter-include/blob/master/README.md#wiki

@Mackiovello do we have any better pages in doc.starcounter.io to link to? or should I just remove those and forget about it?

**Comment by ErlendLandro** [comment]
> @Mackiovello do we have any better pages in doc.starcounter.io to link to? or should I just remove those and forget about it?

I would probably remove them, or you could simply link to the [Blending](https://docs.starcounter.io/guides/blending/) section. The "Related articles" are also shown twice, I would remove one of them.
