### ISSUE TITLE
Elements without `slot="..."` are not rendered

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#49]
### Steps to reproduce

1. Clone KitchenSink
2. Force using the current version of `starcounter-include`:

```txt
cd src/KitchenSink
bower install starcounter-include#a08f7ea24e3dffc38cd5072b03b3569227996732
cd ../..
```

3. Make sure to restart the database so that the new `starcounter-include` is used
4. Build and run KitchenSink
5. Go to http://localhost:8080/KitchenSink/Pagination

### Expected result

A table should be rendered below pagination tools 

### Actual result

The table is not rendered.

This was first detected in https://github.com/Starcounter/starcounter-include/pull/45#issuecomment-316429756

### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![](https://user-images.githubusercontent.com/566463/28376450-6edaf070-6caa-11e7-8ec0-3b8764250f28.png)

**Comment by tomalec** [comment]
Please use https://github.com/starcounter/level1/tree/starcounter-include-CEv1 as adding default slot is no longer a responsibility of client side. See release notes https://github.com/Starcounter/starcounter-include/releases/tag/3.0.0-rc.0

**Comment by warpech** [comment]
Got it. This can be closed then.
