### ISSUE TITLE
Improve a warning when view-model is supplied with a non blended partial

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-include#55]
In the last updates of `<starcounter-include>` we removed support for not blended partials, but there is no way for developers to identify such places.

There should be a meaningful JavaScript warning if `view-model` is supplied with a not blended partial. The error message should also indicate that `<template is="imported-template">` has to be used in this case.

@tomalec I assign the issue on you, but feel free to assign on someone else who has to implement it.

**Comment by warpech** [comment]
A simple heuristic would be to check if the response only has values which are objects, especially not a key `Html` with value of type `string`.

**Comment by warpech** [comment]
@miyconst proposes

- include the `starconter-inculde` instance in the `console.error`
- include information about the JSON parent or path to the failing view-model subtree

**Comment by tomalec** [comment]
@miyconst  is that what you need https://github.com/Starcounter/level1/blob/develop/src/BuildSystem/ClientFiles/StaticFiles/sys/starcounter-include/starcounter-include.html#L406 ? It's there for 17days. Do you need anything more (other than adding references to model and instance)? Are you using latest RC?

**Comment by tomalec** [comment]
Already closed issue https://github.com/Starcounter/starcounter-include/issues/29

**Comment by miyconst** [comment]
@tomalec, I am using the latest `2.3.1`, and it fails with a warning on the console, but that warning is extremely difficult to debug, that is why I asked for:

>include the starconter-inculde instance in the console.error
>include information about the JSON parent or path to the failing view-model subtree
