### ISSUE TITLE
Move to Starcounter organisation

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#6]
`starcounter-include` is not a sample app but it is currently in [StarcounterSamples](https://github.com/StarcounterSamples) organisation.

It should be moved to [Starcounter](https://github.com/Starcounter) organisation because it is Starcounter-related custom element.

**Comment by miyconst** [comment]
+1

**Comment by tomalec** [comment]
:+1:

**Comment by warpech** [comment]
The repo was moved today. A new version should be released to mark the change as done.

**Comment by warpech** [comment]
Done
