### ISSUE TITLE
Test suite is flaky

### ISSUE THREAD

**Issue by alshakero** [Starcounter/starcounter-include#61]
See builds:

1- ❌ https://travis-ci.org/Starcounter/starcounter-include/builds/289883476 
2- ✔️ https://travis-ci.org/Starcounter/starcounter-include/builds/289883530 

Both builds are for the same commit (https://github.com/Starcounter/starcounter-include/commit/c4ce9002f8c415311f94a301d5e02be9aaedb253)

Restarting the build fixes the issue, sometimes.

**Comment by tomalec** [comment]
@alshakero  does it still happen? I think `concurrently` may have fixed that.

**Comment by alshakero** [comment]
Haven't happened to me for a long time. I think we can close it now.
