### ISSUE TITLE
⏰ starcounter-include does not work in V1 with browsers other than Chrome

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#69]
This issue is fixed in polyfill here https://github.com/webcomponents/html-imports/pull/77

Until polyfill accepts the PR, @tomalec will make a workaround in starcounter-include

**Comment by tomalec** [comment]
Fixed, and released in `2.4.0.4448` https://github.com/Starcounter/level1/pull/4435

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/starcounter-include/releases/tag/4.1.0
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.0
