### ISSUE TITLE
HTML of a loaded partial is not removed when partial is removed

### ISSUE THREAD

**Issue by miyconst** [Starcounter/starcounter-include#7]
HTML: 

``` html
<starcounter-include partial="{{model.FocusedProject}}"></starcounter-include>
```

The server side:

``` cs
this.FocusedProject = null;
```

Patch to the client:

``` json
[{"op":"replace","path":"/FocusedProject","value":{}}]
```

Browser console:

```
partial.Html for <starcounter-include>​…​</starcounter-include>​ is missing.
```

But the actuall HTML is not removed.

Test bench is available: https://github.com/miyconst/Playground/

**Comment by miyconst** [comment]
https://github.com/Starcounter/starcounter-include/blob/gh-pages/starcounter-include.html#L80

``` js
if (this.isAttached && html) {
    this.template.setAttribute("content", html);
    this.template.model = this.partial;
}
```

Removing `&& html` fixes the issue.

Any possible consequences?

**Comment by warpech** [comment]
Did it work with Polymer 1.1?

**Comment by warpech** [comment]
Does the current code (including `&& html`) work with Polymer 1.1? Or does it only affect 1.2 and 1.3?

**Comment by miyconst** [comment]
No. I just tested. It worked when we replace the partial or load it from empty, but not when removing.

**Comment by miyconst** [comment]
> Removing && html fixes the issue.

Looks like it does not. `<imported-template>` treats `undefined` and `null` as content and creates such piece of html.

`<imported-template>` also not observing `removeAttribute("content")`.

**Comment by warpech** [comment]
@miyconst did you manage to find a solution?

**Comment by miyconst** [comment]
No, I was not looking for it. I would like to hear something from @tomalec before implementing any solution.

**Comment by tomalec** [comment]
I suspect `if (this.isAttached && html) {` may be there to avoid stamping Polymer 0.x `"{{}}"`. I'd say we should definitely forward empty `html`  property or removal to `imported-template`

Regarding removal/setting to null, I think we should add check for `val===null` at https://github.com/Juicy/juicy-html/blob/master/juicy-html.html#L38
and remove the stamped nodes.

**Comment by warpech** [comment]
@tomalec can you do the fix?

**Comment by tomalec** [comment]
We need to find a workaround for https://github.com/webcomponents/webcomponentsjs/issues/498 to make tests pass, probably we will need to apply in completely different custom element: `juicy-tile-*`
