### ISSUE TITLE
Fix and improve changes for sub and superset layouts, PR #67

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#72]
As suggested:
- [ ] 1. https://github.com/Starcounter/starcounter-include/pull/67/files#r156899229
   We should use subset composition even if we don't have `defaultComposition` for remaining elements, just use `<slot>` to make sure they are distributed.
- [ ] 2. https://github.com/Starcounter/starcounter-include/pull/67/files#r156918307
   Use `defaultComposition`  instead of traversing all `scopedNodes`. Consider the map of default compositions per scope.
- [x] 3. Add descriptions for the names of different means to provide a composition https://github.com/Starcounter/starcounter-include/pull/67#discussion_r156894068
- [ ] 4. Add more code comments https://github.com/Starcounter/starcounter-include/pull/67#discussion_r156897576
- [ ] 5. Review `.storedLayout` problem https://github.com/Starcounter/starcounter-include/pull/67#discussion_r156893474

@warpech volunteered be the reviewer

**Comment by warpech** [comment]
PR #67 also has few more comments about README and declaring public properties, please also apply these.

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
