### ISSUE TITLE
Fix Polymer notification cases broken by #62

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#75]
I have found that `_notifyPath` was oversimplified and is missing some cases, like:
- when Polymer changes sub-partial to one that changes the URL, model should not be notified immediately,
- when Polymer changes sub-partial's HTML, model should not be notified immediately.
- when Polymer changes sub-partial to one that does not change the URL, imported-template should be notified immediately about the change,

**Comment by tomalec** [comment]
Fix and released in `2.4.0.4448` https://github.com/Starcounter/level1/pull/4435

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/starcounter-include/releases/tag/4.1.0
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.0
