### ISSUE TITLE
Prepare for working with BlendingProvider

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#79]
Starting from this week, the composition information can be delivered in one of the following JSON keys:

```txt
CompositionProvider
CompositionProvider_0
BlendingProvider_0
BlendingProvider_1
```

Please prepare `starcounter-include` for searching for the composition information in all of the above combinations. The key will not change during the session, so if you use searching, it can be searched once.

This is a requirement of https://github.com/Starcounter/RebelsLounge/issues/232.

**Comment by warpech** [comment]
~~Please note that we need the fix for both CEv0 and CEv1 version of `starcounter-include`.~~

~~The fix for CEv0 version should not delegate the responsibility to set the namespace name on the outside of `starcounter-include`, because that's a too big change.~~

**Comment by tomalec** [comment]
by "CEv0 version" do you mean 
1. `3.0.0` `starcounter-include` [used in StarcounterClientFiles@`1.x`](https://github.com/Starcounter/StarcounterClientFiles/blob/1.x/src/StarcounterClientFiles/wwwroot/sys/starcounter-include/starcounter-include.html) and in [level1](https://github.com/Starcounter/level1/blob/develop/src/BuildSystem/ClientFiles/StaticFiles/sys/starcounter-include/starcounter-include.html). Version that uses CEv1 syntax for itself, relies on `d-r-e`, but uses `imported-tempalte` as CEv0 customized-buildin,
2. `2.4.1` version that uses CEv0 top to bottom, and is used in old versions of level1?

**Comment by tomalec** [comment]
Or maybe you meant Polymer 1 and Polymer 2?

**Comment by warpech** [comment]
I mean `3.0.0`

**Comment by warpech** [comment]
Disregard my comment https://github.com/Starcounter/starcounter-include/issues/79#issuecomment-355016293, we only need this in `starcounter-include` 4.x, because BlendingProvider will only be released for Starcounter 2.4 and Polymer 2.

**Comment by tomalec** [comment]
Released in https://github.com/Starcounter/starcounter-include/releases/tag/4.2.0

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/starcounter-include/releases/tag/4.2.0
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.0
