### ISSUE TITLE
Shadow DOM (ShadyCSS) styles bleeds in polyfilled browsers

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#82]
As discovered in
- https://github.com/Starcounter/starcounter-include/issues/81 
 - https://github.com/webcomponents/webcomponentsjs/issues/883

style scoping is broken in polyfilled browsers.

- :+1: the tests are failing only for compositions that comes from a string (database) not from a `<template>` (`declarative-shadow-dom`), most problably in worst case we could workit around with a overhead of creating a `<template>` element to parse a string to `DocumentFragment`
- :-1: the shadow DOM scoping is broken in others as well as even though markup is prepared for scoping, styles are not - I'm still trying to find a way to use limited `ShadyCSS` API to make it work,
- :+1: Firefox shipped CEv1 in nightly, so the should meet their plans to deliver SD and CE natively ca. March (the problem should be solved in FF by native support)
- :+1: Polymer team is planning to rewrite/improve their ShadyCSS polyfill to make it less limited, and expose more sane API, what could just fix our case/provide tools to fix it nice and simple https://github.com/webcomponents/shadycss/issues/134 (no dates given :-1:)

We decided to postpone it and wait for ShadyCSS refactoring and upcoming native support.

### Steps to reproduce
1. Create two separate views with `<button>`,
2. Add a composition (`declarative-shadow-dom`, or `CompositionProvider_0/Composition$`) that contains `<style>button{color:red}</style><button></button>` for one of the views.
3. Display both views on the same page, but not at the same `<starcounter-include>` (blending point).

### Expected result
Only the view with given composition should have a red button.

### Actual result
Both buttons are red

### Browsers affected

- [ ] Chrome
- [x] Firefox
- [x] Edge
- [?] Safari 9
- [?] Safari 8

**Comment by warpech** [comment]
Let's get back to this about a month before releasing Starcounter 2.4 and check where are Firefox and ShadyCSS then.

For the time being, we will have to live with leaky CSS rules in declarative Shadow DOM.

@tomalec can you add an information about the leaky CSS in the README.md of `starcounter-include`?

**Comment by tomalec** [comment]
> @tomalec can you add an information about the leaky CSS in the README.md of starcounter-include?

It's already there https://github.com/Starcounter/starcounter-include/pull/83/files#diff-04c6e90faac2675aa89e2176d2eec7d8L154

**Comment by miyconst** [comment]
Not relevant for Starcounter 3.
