### ISSUE TITLE
starcounter-include does not work inside shadow-root

### ISSUE THREAD

**Issue by malx122** [Starcounter/starcounter-include#84]
### Steps to reproduce
SC 2.4, polymer 2. (Was not a problem in polymer 1.x)
Use <starcounter-include> to import partials inside a webcomponents shadowroot
Some features might work, but at least the script tag fails to fetch the script to add methods e.tc. to the partial.

Used in some nested places. For example our chat app has a web component that handles and show different chat windows depending on screen space e.t.c. But every chat window wants to have some partials from different apps inside them.

- [X ] Chrome

**Comment by warpech** [comment]
@tomalec can you please take a look at this? I think we should make this work.

**Comment by warpech** [comment]
@malx122 how urgent is this? We'd like to postpone it to Q2

**Comment by miyconst** [comment]
Not relevant for Starcounter 3.
