### ISSUE TITLE
Remove Translate-ShadowDOM

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#88]
The current version of starcounter-include no longer has to translate from V0 to V1 or back. As part of cleanup and performance improvement, usage of `Translate-ShadowDOM` should be removed from this repo.

----

I searched in other repos, and Translate-ShadowDOM is also used in:

- https://github.com/Juicy/juicy-composition - let's do nothing about it, because this repo is deprecated
- https://github.com/Starcounter/ViewTranslator - let's do nothing about it, because it is needed in this tool

**Comment by alshakero** [comment]
WIP

**Comment by warpech** [comment]
Closing as done in PR #89
