### ISSUE TITLE
Go through TODOs in the source files

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#92]
The source files have 7 TODOs. Maybe it's a good time to fix some of them or move them to separate issues?

<img width="1024" alt="screen shot 2018-02-23 at 12 14 03" src="https://user-images.githubusercontent.com/566463/36591708-2559a118-1893-11e8-8620-39187440af9f.png">

**Comment by miyconst** [comment]
Won't be fixed, since the component is not relevant for Starcounter 3.
